services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner        # Build tới stage production cuối cùng
    container_name: portfolio-app
    image: ntuananh05/portfolio:latest  # Docker Hub image name
    ports:
      - "3000:3000"         # host:container
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
